services:
  postgres: # database
    build: postgres
    image: postgres:latest
    container_name: postgres
    env_file:
    - .env
    volumes:
    - postgres:/var/lib/postgresql/data/
    ports:
    - "5432"
  uwsgi:
    build: intel_owl
    image: intel_owl:latest
    container_name: uwsgi
    volumes:
    - logs:/var/log/intel_owl
    - web:/opt/deploy/intel_owl/static
    ports:
    - "8001"
    env_file: intel_owl/.env
    depends_on:
    - postgres
# rabbitmq
# celery_beat
# celery_worker
# nginx
# velociraptor
# elasticsearch
# kibana
# grafana
# prometheus
# iris
volumes:
  certs:
    name: certs
  logs:
    name: logs
  postgres:
    name: postgres
  web:
    name: web