services:
  postgres: # database
    build: postgres
    image: postgres:latest
    container_name: postgres
    env_file:
    - .env
    volumes:
    - postgres:/var/lib/postgresql/data/
    ports:
    - "5432"
  intel_owl: # uwsgi is a backend server used to deploy Python apps like intel_owl
    build: intel_owl
    image: intel_owl:latest
    container_name: intel_owl
    env_file:
      - .env
    volumes:
      - logs:/var/log/intel_owl
      #- static_content:/opt/deploy/intel_owl/static
      #- shared_files:/opt/deploy/files_required
    ports:
      - "8001"
    depends_on:
      - postgres
# rabbitmq
# celery_beat
# celery_worker
# nginx
# velociraptor
# elasticsearch
# kibana
# grafana
# prometheus
# iris
volumes:
  certs:
    name: certs
  logs:
    name: logs
  postgres:
    name: postgres
  web:
    name: web