services:
  velociraptor: 
    profiles: [ "velocistack", "velociraptor" ]
    build: velociraptor
    image: velociraptor:dev
    container_name: velociraptor
    hostname: velociraptor
    env_file: .env
    volumes:
      - velociraptor_data:/opt/velociraptor/
      - velociraptor_api:/api/
    ports:
      - "8000:8000" # server-to-client communication
      - "8001:8001" # gRPC server (handles API request)
      - "8003:8003" # Prometheus monitoring server
      - "443:443"   # web console
  #cyber-chef: 
  #  profiles: [ "velocistack", "cyber-chef" ]
  #  build: cyber-chef
  #  image: cyber-chef:dev
  #  container_name: cyber-chef
  #  hostname: cyber-chef
  #  ports:
  #    - "8443:8443"
  postgres: # database
    profiles: [ "velocistack", "intelowl", "iris", "postgres" ]
    build: postgres
    image: postgres:dev
    container_name: postgres
    hostname: postgres
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB_INTELOWL" ]
      start_period: 10s
      interval: 10s
      timeout: 3s
      retries: 3
  rabbitmq: # message broker between (Nginx > uWSGI > Intel Owl) and Celery
    profiles: [ "velocistack", "intelowl" ]
    build: rabbitmq
    image: rabbitmq:dev
    container_name: rabbitmq
    hostname: rabbitmq
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping -q"]
      start_period: 10s
      interval: 10s
      timeout: 3s
      retries: 3
  celery-beat: # schedules tasks for Intel Owl; sends results to Postgres
    profiles: [ "velocistack", "intelowl" ]
    build: celery-beat
    image: celery-beat:dev
    container_name: celery-beat
    hostname: celery-beat
    env_file: .env
    volumes:
      - logs:/var/log/intel_owl/
      - shared:/opt/deploy/files_required
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  # healthcheck:
  #   test: ["CMD-SHELL", "ps aux | grep -i '[c]elery"]
  #   start_period: 10s
  #   interval: 10s
  #   timeout: 3s
  #   retries: 3
  celery-worker: # off-loads tasks for Intel Owl; sends results to Postgres
    profiles: [ "velocistack", "intelowl" ]
    build: celery-worker
    image: celery-worker:dev
    container_name: celery-worker
    hostname: celery-worker
    env_file: .env
    volumes:
      - logs:/var/log/intel_owl/
      - shared:/opt/deploy/files_required
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  # healthcheck:
  #   test: ["CMD-SHELL", "ps aux | grep -i '[c]elery"]
  #   start_period: 10s
  #   interval: 10s
  #   timeout: 3s
  #   retries: 3
  intelowl: # Web Server Gateway Interface between Nginx and Intel Owl (a Python/Django-based app)
    profiles: [ "velocistack", "intelowl" ]
    build: intelowl
    image: intelowl:dev
    container_name: intelowl
    hostname: intelowl
    env_file: .env
    volumes:
      - logs:/var/log/intel_owl/
      - web:/opt/deploy/intel_owl/static/
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      celery-beat:
        condition: service_started
      celery-worker:
        condition: service_started
  iris:
    profiles: [ "velocistack", "iris" ]
    build: iris
    image: iris:dev
    container_name: iris
    hostname: iris
    env_file: .env
    ports:
     - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
  nginx: # front-end web server
    profiles: [ "velocistack", "intelowl", "iris" ]
    build: nginx
    image: nginx:dev
    container_name: nginx
    hostname: nginx
    volumes:
      - certs:/etc/nginx/ssl/
      - logs:/var/log/nginx/
      - web:/var/www/static/
    ports:
      - "8080:8080"
    depends_on:
      - intelowl # upstream server needs to be up first for redirection
      - iris
  elasticsearch:
    profiles: [ "velocistack", "elastic" ]
    build: elasticsearch
    image: elasticsearch:dev
    container_name: elasticsearch
    hostname: elasticsearch
    env_file: .env
    volumes:
      - certs:/usr/share/elasticsearch/config/certs/
    # - logs:/var/log/elasticsearch
    ports:
      - "9200:9200"
    networks: 
      velocistack:
        ipv4_address: ${ES_IP}
    #healthcheck:
    #  test: ["CMD-SHELL", "curl ${ES_HOST} --cacert ${ES_PUBLIC_KEY} -u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"]
    #  start_period: 10s
    #  retries: 3
    #  interval: 5s
    #  timeout: 3s
  kibana:
    profiles: [ "velocistack", "elastic" ]
    build: kibana
    image: kibana:dev
    container_name: kibana
    hostname: kibana
    env_file: .env
    volumes:
      - certs:/usr/share/kibana/config/certs/
    # - logs:/var/log/elasticsearch
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    extra_hosts:
      - "elasticsearch:${ES_IP}"
    networks: 
      velocistack:
        ipv4_address: ${KIBANA_IP}
    depends_on:
      - elasticsearch
      # elasticsearch:
      #   condition: service_healthy
    #healthcheck:
    #  test: [ "CMD-SHELL", "curl http://${KIBANA_IP}:${KIBANA_PORT} -I -s | grep -q 'HTTP/1.1 302 Found'", ]
  #cadvisor:
  #  profiles: [ "velocistack", "prometheus" ] 
  #  build: cadvisor
  #  image: cadvisor:dev 
  #  container_name: cadvisor
  #  hostname: cadvisor
  #  ports:
  #    - "8080:8080"
  prometheus:
    profiles: [ "velocistack", "prometheus" ]
    build: prometheus
    image: prometheus:dev
    container_name: prometheus
    hostname: prometheus
    env_file: .env
    ports:
      - "9090:9090"
    # depends_on:
    #   - cadvisor
  grafana:
    profiles: [ "velocistack", "grafana" ]
    build: grafana
    image: grafana:dev
    container_name: grafana
    hostname: grafana
    env_file: .env
    ports:
      - "3000:3000"

volumes:
  certs:
    name: certs
  logs:
    name: logs
  postgres:
    name: postgres
  web: 
    name: web
  shared:
    name: shared
  velociraptor_data:
    name: velociraptor_data
  velociraptor_api:
    name: velociraptor_api

networks:
  velocistack:
    name: velocistack
    ipam: 
      config: 
        - subnet: ${SUBNET}