# Dockerfile metadata
FROM prom/prometheus
LABEL maintainer="Wes Lambert, @therealwlambert"
LABEL contributor="Victor Fernandez III, @cyberphor"

# Copy Prometheus configuration file
COPY prometheus.yml /etc/prometheus/prometheus.yml