# Dockerfile metadata
FROM rabbitmq:3
LABEL maintainer="Wes Lambert, @therealwlambert"
LABEL contributor="Victor Fernandez III, @cyberphor"

# TODO: fix
# amqp://guest:**@rabbitmq:5672//: [Errno 111] Connection refused.