# Dockerfile metadata
FROM postgres:12
LABEL maintainer="Wes Lambert, @therealwlambert"
LABEL contributor="Victor Fernandez III, @cyberphor"

COPY create_user.sh  /docker-entrypoint-initdb.d/10-create_user.sh