# Dockerfile metadata
FROM postgres:12
LABEL maintainer="Wes Lambert, @therealwlambert"
LABEL contributor="Victor Fernandez III, @cyberphor"

# Copy init script
COPY velocistack.sh /docker-entrypoint-initdb.d/velocistack.sh